import { Dom } from "./Libs.js";

let Src = {
    // New src content added here

    // * New Images added here
    arrow_1: new Dom("#arrow_1"),
    arrow_2: new Dom("#arrow_2"),
    bat_list_1: new Dom("#bat_list_1"),
    bat_list_1_heading: new Dom("#bat_list_1_heading"),
    bat_list_2: new Dom("#bat_list_2"),
    bat_list_2_heading: new Dom("#bat_list_2_heading"),
    binding_key: new Dom("#binding_key"),
    black_arrow_1: new Dom("#black_arrow_1"),
    black_arrow_2: new Dom("#black_arrow_2"),
    btn_start_rectifying: new Dom("#btn_start_rectifying"),
    btn_start_tracing_1: new Dom("#btn_start_tracing_1"),
    btn_start_tracing_2: new Dom("#btn_start_tracing_2"),
    drone_3d_img: new Dom("#drone_3d_img"),
    drone_back_side: new Dom("#drone_back_side"),
    drone_front_side: new Dom("#drone_front_side"),
    drone_front_side_after_removing_upper_plate: new Dom("#drone_front_side_after_removing_upper_plate"),
    flight_controller_zoom_img: new Dom("#flight_controller_zoom_img"),
    front_page_box: new Dom("#front_page_box"),
    fullfinal_drone: new Dom("#fullfinal_drone"),
    intro_page: new Dom("#intro_page"),
    issue_1: new Dom("#issue_1"),
    issue_2: new Dom("#issue_2"),
    issue_bat: new Dom("#issue_bat"),
    issue_battery_listings: new Dom("#issue_battery_listings"),
    issue_pmu: new Dom("#issue_pmu"),
    mask: new Dom("#mask"),
    pmuzoom: new Dom("#pmuzoom"),
    pmu_img: new Dom("#pmu_img"),
    popup_1: new Dom("#popup_1"),
    popup_2: new Dom("#popup_2"),
    problem_1: new Dom("#problem_1"),
    problem_1_battery: new Dom("#problem_1_battery"),
    problem_1_battery_puffed: new Dom("#problem_1_battery_puffed"),
    problem_1_drone_front_image: new Dom("#problem_1_drone_front_image"),
    problem_1_drone_front_with_pmu_image: new Dom("#problem_1_drone_front_with_pmu_image"),
    problem_1_drone_front_zoom_image: new Dom("#problem_1_drone_front_zoom_image"),
    problem_1_drone_front_zoom_image_2: new Dom("#problem_1_drone_front_zoom_image_2"),
    problem_1_pmu_zoom_img_2: new Dom("#problem_1_pmu_zoom_img_2"),
    problem_1_soldering_iron_of_connector: new Dom("#problem_1_soldering_iron_of_connector"),
    problem_2: new Dom("#problem_2"),
    receiver_zoom_img: new Dom("#receiver_zoom_img"),
    right_tick_1: new Dom("#right_tick_1"),
    right_tick_2: new Dom("#right_tick_2"),
    right_tick_3: new Dom("#right_tick_3"),
    right_tick_4: new Dom("#right_tick_4"),
    round_arrow: new Dom("#round_arrow"),
    step_1_arrow_image_1: new Dom("#step_1_arrow_image_1"),
    step_1_arrow_image_2: new Dom("#step_1_arrow_image_2"),
    tab_1: new Dom("#tab_1"),
    tab_2: new Dom("#tab_2"),
    tab_3: new Dom("#tab_3"),
    tab_4: new Dom("#tab_4"),
    tab_dot: new Dom("#tab_dot"),
    tie: new Dom("#tie"),
    tie_tied: new Dom("#tie_tied"),
    transmitter: new Dom("#transmitter"),
    wire4arm_pmufix: new Dom("#wire4arm_pmufix"),
    zoompmu: new Dom("#zoompmu"),
    zoom_battery_with_bcg_and_border: new Dom("#zoom_battery_with_bcg_and_border"),
    zoom_without_battery_and_border: new Dom("#zoom_without_battery_and_border"),

    // * New Videos added here
    battery_remove: new Dom("#battery_remove"),
    binding: new Dom("#binding"),
    send_dropping: new Dom("#send_dropping"),
    yoke_front_to_back: new Dom("#yoke_front_to_back"),
    yoke_front_to_side: new Dom("#yoke_front_to_side"),
}

export default Src;
